### ISSUE TITLE
Fonts with executable permissions

### ISSUE THREAD

**Issue by mensfeld** [NaiveCAI/material_admin_rails#6]
While analyzing this repository I've noticed, that there are font files with executable permissions:
```
vendor/rails_material_admin/css/icon/font-awesome/webfonts/fa-brands-400.eot-
data/vendor/rails_material_admin/css/icon/font-awesome/webfonts/fa-solid-900.eot-
```

Should the fonts be executable?

**Comment by NaiveCAI** [comment]
Apparently not @mensfeld

**Comment by mensfeld** [comment]
@NaiveCAI thank you for your answer. Do you want me to fix this in a pull request?

**Comment by NaiveCAI** [comment]
That would be great, thank you @mensfeld

**Comment by mensfeld** [comment]
Hey there, despite me fixing them I can again see those in the most recent release ;(

though only two:

```
vendor/rails_material_admin/css/icon/font-awesome/webfonts/fa-brands-400.eot-
vendor/rails_material_admin/css/icon/font-awesome/webfonts/fa-solid-900.eot-
```
